"""add idempotency key transfer id and schema updates

Revision ID: 19e2d4494efc
Revises: 7b57ea1fb58c
Create Date: 2026-09-21 23:06:01.704529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e2d4494efc'
down_revision: Union[str, None] = '7b57ea1fb58c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transfer_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'transfers', ['transfer_id'], ['id'])
    op.add_column('transfers', sa.Column('idempotency_key', sa.String(length=64), nullable=False))
    op.add_column('transfers', sa.Column('description', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uq_transfer_idempotency_key', 'transfers', ['idempotency_key'])
    op.create_unique_constraint(None, 'transfers', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfers', type_='unique')
    op.drop_constraint('uq_transfer_idempotency_key', 'transfers', type_='unique')
    op.drop_column('transfers', 'description')
    op.drop_column('transfers', 'idempotency_key')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'transfer_id')
    # ### end Alembic commands ###
