"""add foreign key account id on payment table

Revision ID: b9cf913d1bb3
Revises: f6cb81ac0355
Create Date: 2026-09-21 14:22:25.946216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9cf913d1bb3'
down_revision: Union[str, None] = 'f6cb81ac0355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('account_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'payments', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'account_id')
    # ### end Alembic commands ###
